<a href="https://colab.research.google.com/github/siddharth10-dev/data-viz-python/blob/main/DATA_DAY1ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys
import numpy as np

In [ ]:
#comment of the data

In [ ]:
print("data day 1")


data day 1


In [ ]:
a = np.array([1,2,3,4])
print(a[0],a[1])

1 2


In [ ]:
a[0:]

array([1, 2, 3, 4])

In [ ]:
a[1:3]

array([2, 3])

In [ ]:
a[::2]

array([1, 3])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b=np.array([0.5,0.1,1.5])

In [ ]:
b[1:]

array([0.1, 1.5])

In [ ]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [ ]:
A.shape

(2, 3)

In [ ]:
A.ndim

2

In [ ]:
A.size

6

In [ ]:
A = np.arange(5)
A+20

array([20, 21, 22, 23, 24])

In [ ]:
B=np.arange(6)
B

array([0, 1, 2, 3, 4, 5])

In [ ]:
B+30

array([30, 31, 32, 33, 34, 35])

In [ ]:
B=B+30

In [ ]:
B

array([30, 31, 32, 33, 34, 35])

In [ ]:
#BOOLEAN ARRAYS(masks)

In [ ]:
c = np.arange(5)

In [ ]:
c<=3

array([ True,  True,  True,  True, False])